version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.2.0
  aws-ecs: circleci/aws-ecs@0.0.15

jobs:
  # Define job update $TIME Project enviroment variable
  update-project-enviroment-variable:
    docker:
      - image: circleci/buildpack-deps:stretch
#    machine:
#      image: ubuntu-1604:201903-01
    steps:
      - setup_remote_docker
      - run:
          name: update timezone to Asia/Tokyo
          command: |
            timedatectl

            timedatectl set-timezone Asia/Tokyo
      - run:
          name: delete old $TIME variable
          command: |
            curl -X DELETE https://circleci.com/api/v1.1/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/envvar/TIME -H "Circle-Token: $CIRCLE_TOKEN"
      - run:
          name: create new $TIME variable
          command: |
            touch time.sh
            chmod +x time.sh
            echo '#!/bin/bash' >> time.sh
            echo "curl -X POST --header \"Content-Type: application/json\" -d '{\"name\":\"TIME\", \"value\":\"$(date "+%Y-%m-%dT%H-%M-%S")\"}' https://circleci.com/api/v1.1/project/gh/$CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME/envvar -H \"Circle-Token: $CIRCLE_TOKEN\"" >> time.sh
            cat time.sh
            ./time.sh

  # Define our jobs by reuse jobs of ecr and ecs orbs 
  build-and-push-image-user-front-nginx: aws-ecr/build-and-push-image
  build-and-push-image-user-front: aws-ecr/build-and-push-image
  deploy-service-user-front: aws-ecs/deploy-service-update

workflows:
  # 1. BUILD AND DEPLOY "USER_FRONT" TASK
  build_and_deploy_user_front:
    jobs:
      # --- Prepare env ---------
      - update-project-enviroment-variable:
          context: "vivit-<< pipeline.git.branch >>"
